package core;

public class HardCodedAcronymMapLoader implements AcronymMapLoader {

    @Override
    public void load(AcronymMap map) {
        map.add(new AcronymDetail("BbA", "Better by Adobe"));
        map.add(new AcronymDetail("Trwnbts", "The road will never be the same"));
        map.add(new AcronymDetail("Aaiaw", "Ask about it at work"));
        map.add(new AcronymDetail("Wkm", "We know money"));
        map.add(new AcronymDetail("Std", "Stronger than dirt"));
        map.add(new AcronymDetail("IcbIatwt", "I can’t believe I ate the whole thing"));
        map.add(new AcronymDetail("Mmtsm", "Mama mia, thatsa spicy meatball"));
        map.add(new AcronymDetail("Tiyli", "Try it, you’ll like it"));
        map.add(new AcronymDetail("Trgo", "The relief goes on"));
        map.add(new AcronymDetail("YighwA", "You’re in good hands with Allstate"));
        map.add(new AcronymDetail("DyddA", "Doesn’t your dog deserve Alpo?"));
        map.add(new AcronymDetail("Wlad", "Works like a dream"));
        map.add(new AcronymDetail("Ssita", "Something special in the air"));
        map.add(new AcronymDetail("Btpoc", "Behold the power of cheese"));
        map.add(new AcronymDetail("Dlhwi", "Don’t leave home without it"));
        map.add(new AcronymDetail("Dm", "Do more"));
        map.add(new AcronymDetail("MlMc", "My life My card"));
        map.add(new AcronymDetail("Ffffr", "For fast, fast, fast relief"));
        map.add(new AcronymDetail("Lr", "Legendary reliability"));
        map.add(new AcronymDetail("Td", "Think different"));
        map.add(new AcronymDetail("Tptbyb", "The power to be your best"));
        map.add(new AcronymDetail("Totb", "Think outside the box"));
        map.add(new AcronymDetail("Roats", "Reach out and touch someone"));
        map.add(new AcronymDetail("Twnc", "The world’s networking company"));
        map.add(new AcronymDetail("Nf", "Never follow"));
        map.add(new AcronymDetail("Wth", "We try harder"));
        map.add(new AcronymDetail("Hs", "Higher standards"));
        map.add(new AcronymDetail("Tyfys", "Thank you for your support"));
        map.add(new AcronymDetail("Bww", "Bayer works wonders"));
        map.add(new AcronymDetail("FmB", "Flick my Bic"));
        map.add(new AcronymDetail("Wmc", "We mean clean"));
        map.add(new AcronymDetail("LmCiu", "Life’s messy Clean it up!"));
        map.add(new AcronymDetail("Sdp", "Sheer driving pleasure"));
        map.add(new AcronymDetail("Tudm", "The ultimate driving machine"));
        map.add(new AcronymDetail("Bstr", "Better sound through research"));
        map.add(new AcronymDetail("Tqp", "The quicker picker-upper"));
        map.add(new AcronymDetail("Wygifi", "When you’ve got it, flaunt it"));
        map.add(new AcronymDetail("FittrwB", "Fill it to the rim with Brim"));
        map.add(new AcronymDetail("Htatmom", "Hope, triumph, and the miracle of medicine"));
        map.add(new AcronymDetail("Twtf", "The way to fly"));
        map.add(new AcronymDetail("Twfa", "The world’s favourite airline"));
        map.add(new AcronymDetail("W", "Wassup?!"));
        map.add(new AcronymDetail("Tkob", "The king of beers"));
        map.add(new AcronymDetail("Ijtb", "It just tastes better"));
        map.add(new AcronymDetail("Hiyw", "Have it your way"));
        map.add(new AcronymDetail("Bt", "Break through"));
        map.add(new AcronymDetail("Acawtawa", "A can a week, that’s all we ask"));
        map.add(new AcronymDetail("Gm", "Got milk?"));
        map.add(new AcronymDetail("Ctma", "Calgon, take me away"));
        map.add(new AcronymDetail("Blamlo", "Between love and madness lies obsession"));
        map.add(new AcronymDetail("NcbmamC", "Nothing comes between me and my Calvins"));
        map.add(new AcronymDetail("Iwamfac", "I’d walk a mile for a camel"));
        map.add(new AcronymDetail("Fnp", "For negative people"));
        map.add(new AcronymDetail("Wiyw", "What’s in your wallet?"));
        map.add(new AcronymDetail("Fvsd", "For virtually spotless dishes"));
        map.add(new AcronymDetail("Tpie", "Turning partnership into energy"));
        map.add(new AcronymDetail("PdstC", "Please don’t squeeze the Charmin"));
        map.add(new AcronymDetail("Gyob", "Get your own box"));
        map.add(new AcronymDetail("Asml", "A silly millimeter longer"));
        map.add(new AcronymDetail("Lar", "Like a rock"));
        map.add(new AcronymDetail("InntfMN", "It’s not nice to fool Mother Nature"));
        map.add(new AcronymDetail("Ics", "Inspiration comes standard"));
        map.add(new AcronymDetail("Wybr", "Will you be ready?"));
        map.add(new AcronymDetail("EtIg", "Empowering the Internet generation"));
        map.add(new AcronymDetail("Lr", "Live richly"));
        map.add(new AcronymDetail("IIoollmliaab", "If I’ve only one life, let me live it as a blonde"));
        map.add(new AcronymDetail("Dsods", "Does she or doesn’t she?"));
        map.add(new AcronymDetail("Tafc", "The antidote for civilization"));
        map.add(new AcronymDetail("Tsfcat", "The source for computing and technology"));
        map.add(new AcronymDetail("Tmtnin", "The most trusted name in news"));
        map.add(new AcronymDetail("Cryb", "Coca-Cola refreshes you best"));
        map.add(new AcronymDetail("Tptr", "The pause that refreshes"));
        map.add(new AcronymDetail("Hacas", "Have a coke and smile"));
        map.add(new AcronymDetail("Tsb", "The silver bullet"));
        map.add(new AcronymDetail("CTfool", "Cotton The fabric of our lives"));
        map.add(new AcronymDetail("Iywtcsaw", "If you want to capture someone’s attention, whisper"));
        map.add(new AcronymDetail("Hbsfl", "Healthy, beautiful smiles for life"));
        map.add(new AcronymDetail("LMnc", "Look, Ma, no cavities!"));
        map.add(new AcronymDetail("CwktC", "Cooks who know trust Crisco"));
        map.add(new AcronymDetail("Lifl", "Love it for life"));
        map.add(new AcronymDetail("Adif", "A diamond is forever"));
        map.add(new AcronymDetail("EaD", "Easy as Dell"));
        map.add(new AcronymDetail("Yltwwf", "You’ll love the way we fly"));
        map.add(new AcronymDetail("Wltfais", "We love to fly and it shows"));
        map.add(new AcronymDetail("Wcn", "We’re cooking now"));
        map.add(new AcronymDetail("Rtjom", "Restoring the joy of motion"));
        map.add(new AcronymDetail("Wmtw", "We move the world"));
        map.add(new AcronymDetail("YTnB", "Yellow The new Brown"));
        map.add(new AcronymDetail("CBftGfy", "Competition Bad for them Great for you"));
        map.add(new AcronymDetail("AygyuDDywed", "Aren’t you glad you use Dial? Don’t you wish everybody did?"));
        map.add(new AcronymDetail("Thpoe", "The happiest place on earth"));
        map.add(new AcronymDetail("Ttmtd", "Time to make the doughnuts"));
        map.add(new AcronymDetail("Tmos", "The miracles of science"));
        map.add(new AcronymDetail("Bltc", "Better living through chemistry"));
        map.add(new AcronymDetail("Tpoaou", "The power of all of us"));
        map.add(new AcronymDetail("Twom", "The world’s online marketplace"));
        map.add(new AcronymDetail("WEHtpl", "When EF Hutton talks, people listen"));
        map.add(new AcronymDetail("NslaE", "Nothing sucks like an Electrolux"));
        map.add(new AcronymDetail("Wycfc", "When you’re crazy for chicken"));
        map.add(new AcronymDetail("Ikgagag", "It keeps going, and going, and going"));
        map.add(new AcronymDetail("Sywf", "See your way forward"));
        map.add(new AcronymDetail("Qiewd", "Quality in everything we do"));
        map.add(new AcronymDetail("Patiyt", "Put a tiger in your tank"));
        map.add(new AcronymDetail("DjtTr", "Don’t just travel Travel right"));
        map.add(new AcronymDetail("Gtietr", "Good taste is easy to recognize"));
        map.add(new AcronymDetail("ObitAd", "Our business is the American dream"));
        map.add(new AcronymDetail("RiF", "Relax, it’s FedEx"));
        map.add(new AcronymDetail("Twot", "The world on time"));
        map.add(new AcronymDetail("Wiaphtbto", "When it absolutely, positively has to be there overnight"));
        map.add(new AcronymDetail("PLG", "Play Laugh Grow"));
        map.add(new AcronymDetail("Injfba", "It’s not just for breakfast anymore"));
        map.add(new AcronymDetail("Bftra", "Built for the road ahead"));
        map.add(new AcronymDetail("Fhabi", "Ford has a better idea"));
        map.add(new AcronymDetail("Qijo", "Quality is job one"));
        map.add(new AcronymDetail("F–Afb", "Fosters – Australian for beer"));
        map.add(new AcronymDetail("Fab", "Fair and balanced"));
        map.add(new AcronymDetail("Eif", "Extinct is forever"));
        map.add(new AcronymDetail("Siwf", "Say it with flowers"));
        map.add(new AcronymDetail("Iaw", "Imagination at work"));
        map.add(new AcronymDetail("Wbgttl", "We bring good things to life"));
        map.add(new AcronymDetail("Ctmoyl", "Celebrate the moments of your life"));
        map.add(new AcronymDetail("Twttw", "Two words to the wise"));
        map.add(new AcronymDetail("Baob", "Babies are our business"));
        map.add(new AcronymDetail("SybbaGb", "Shouldn’t your baby be a Gerber baby?"));
        map.add(new AcronymDetail("MwItIkh", "My wife, I think I’ll keep her"));
        map.add(new AcronymDetail("Lsfs", "Look sharp, feel sharp"));
        map.add(new AcronymDetail("Tbamcg", "The best a man can get"));
        map.add(new AcronymDetail("Nl‘sys", "Never let ‘em see you sweat"));
        map.add(new AcronymDetail("DgmGG", "Don’t get mad Get GLAD"));
        map.add(new AcronymDetail("TbtitwhGwaot", "The best tires in the world have Goodyear written all over them"));
        map.add(new AcronymDetail("Ltdtu", "Leave the driving to us"));
        map.add(new AcronymDetail("PmdyhaGP", "Pardon me, do you have any Grey Poupon?"));
        map.add(new AcronymDetail("Iagttba", "It’s a great time to be alive"));
        map.add(new AcronymDetail("DbvafH", "Don’t be vague, ask for Haig"));
        map.add(new AcronymDetail("Wycetstvb", "When you care enough to send the very best"));
        map.add(new AcronymDetail("AbbRbc", "American by birth Rebel by choice"));
        map.add(new AcronymDetail("HHaanHP", "Hey! How about a nice Hawaiian Punch?"));
        map.add(new AcronymDetail("Wataha", "We answer to a higher authority"));
        map.add(new AcronymDetail("Hpyitds", "Hertz puts you in the driver’s seat"));
        map.add(new AcronymDetail("5v", "57 varieties"));
        map.add(new AcronymDetail("I", "Invent"));
        map.add(new AcronymDetail("Pptwo", "Pleasing people the world over"));
        map.add(new AcronymDetail("Tpod", "The power of dreams"));
        map.add(new AcronymDetail("Wtcf", "Where’s the cream filling?"));
        map.add(new AcronymDetail("Wbyesotw", "We’re behind you every step of the way"));
        map.add(new AcronymDetail("Sfasp", "Solutions for a small planet"));
        map.add(new AcronymDetail("II", "Intel Inside"));
        map.add(new AcronymDetail("MybIlit", "Manly yes, but I like it, too"));
        map.add(new AcronymDetail("PcpI", "Pure clean, pure Ivory"));
        map.add(new AcronymDetail("9p", "9944% pure"));
        map.add(new AcronymDetail("Jb", "Jack’s back!"));
        map.add(new AcronymDetail("DdiDi", "Don’t dream it Drive it"));
        map.add(new AcronymDetail("Amfd", "America’s most famous dessert"));
        map.add(new AcronymDetail("NrlaD", "Nothing runs like a Deere"));
        map.add(new AcronymDetail("Trrie", "The right relationship is everything"));
        map.add(new AcronymDetail("1jf1k", "100% juice for 100% kids"));
        map.add(new AcronymDetail("T", "Thrive"));
        map.add(new AcronymDetail("EkbwK", "Every kiss begins with Kay"));
        map.add(new AcronymDetail("Tg", "They’re g-r-r-r-eat!"));
        map.add(new AcronymDetail("Sas", "Start aging smart"));
        map.add(new AcronymDetail("Fg", "Finger-lickin’ good!"));
        map.add(new AcronymDetail("NdclK", "Nobody does chicken like KFC"));
        map.add(new AcronymDetail("KtMa", "Kid tested Mother approved"));
        map.add(new AcronymDetail("SmSl", "Share moments Share life"));
        map.add(new AcronymDetail("Itfc", "It’s time for clarity"));
        map.add(new AcronymDetail("Whhsh", "What happens here, stays here"));
        map.add(new AcronymDetail("Bcejo", "Betcha can’t eat just one"));
        map.add(new AcronymDetail("Wbcyw", "When banks compete, you win"));
        map.add(new AcronymDetail("Trpop", "The relentless pursuit of perfection"));
        map.add(new AcronymDetail("IfaIcgu", "I’ve fallen and I can’t get up"));
        map.add(new AcronymDetail("HMli", "Hey, Mikeyhe likes it!"));
        map.add(new AcronymDetail("Aabbnab", "Always a bridesmaid, but never a bride"));
        map.add(new AcronymDetail("BIwi", "Because I’m worth it"));
        map.add(new AcronymDetail("Md", "Magically delicious"));
        map.add(new AcronymDetail("LSmft", "Lucky Strike means fine tobacco"));
        map.add(new AcronymDetail("Cvttc", "Creating value through true convergence"));
        map.add(new AcronymDetail("Miymniyh", "Melts in your mouth, not in your hands"));
        map.add(new AcronymDetail("CtMC", "Come to Marlboro Country"));
        map.add(new AcronymDetail("TasttmcbFeetM", "There are some things that money can’t buy For everything else there’s MasterCard"));
        map.add(new AcronymDetail("Gttld", "Good to the last drop"));
        map.add(new AcronymDetail("IwmM", "I want my Maypo"));
        map.add(new AcronymDetail("Oratlgit", "Our repairmen are the loneliest guys in town"));
        map.add(new AcronymDetail("Pftr", "Passion for the road"));
        map.add(new AcronymDetail("DssM", "Did somebody say McDonald’s?"));
        map.add(new AcronymDetail("IiloiiM", "Is it live or is it Memorex?"));
        map.add(new AcronymDetail("Tsgcafibn", "Tastes so good cats ask for it by name"));
        map.add(new AcronymDetail("MiboA", "Merrill-Lynch is bullish on America"));
        map.add(new AcronymDetail("Mmgm", "MGM means great movies"));
        map.add(new AcronymDetail("Bsmiroyt", "Because so much is riding on your tires"));
        map.add(new AcronymDetail("LtcNtt", "Lose the carbs Not the taste"));
        map.add(new AcronymDetail("YpOp", "Your potential Our passion"));
        map.add(new AcronymDetail("Wdywtgt", "Where do you want to go today?"));
        map.add(new AcronymDetail("IMt", "It’s Miller time!"));
        map.add(new AcronymDetail("Tcobb", "The champagne of bottled beer"));
        map.add(new AcronymDetail("EyawiabAl", "Everything you always wanted in a beer And less"));
        map.add(new AcronymDetail("Tglf", "Tastes great, less filling"));
        map.add(new AcronymDetail("Wuad", "Wake up and drive"));
        map.add(new AcronymDetail("Ocaat", "One client at a time"));
        map.add(new AcronymDetail("Wirip", "When it rains, it pours"));
        map.add(new AcronymDetail("Mwm", "Medicine with muscle"));
        map.add(new AcronymDetail("DtD", "Do the Dew"));
        map.add(new AcronymDetail("BIwfd", "Beef It’s what’s for dinner"));
        map.add(new AcronymDetail("Tabooc", "Take a bite out of crime"));
        map.add(new AcronymDetail("PTowm", "Pork The other white meat"));
        map.add(new AcronymDetail("YclalfadBu", "You could learn a lot from a dummy Buckle up!"));
        map.add(new AcronymDetail("MsT", "Must see TV"));
        map.add(new AcronymDetail("Booto", "Break out of the ordinary"));
        map.add(new AcronymDetail("IlNY", "I love New York"));
        map.add(new AcronymDetail("Atntftp", "All the news that’s fit to print"));
        map.add(new AcronymDetail("Jdi", "Just do it"));
        map.add(new AcronymDetail("Athoti", "At the heart of the image"));
        map.add(new AcronymDetail("OffakNL", "Only fit for a king Nine Lives"));
        map.add(new AcronymDetail("Etr", "Enjoy the ride"));
        map.add(new AcronymDetail("Cp", "Connecting people"));
        map.add(new AcronymDetail("Tiao", "Take it all off"));
        map.add(new AcronymDetail("Tnsscashfsycrm", "The nighttime sniffling sneezing coughing aching stuffy head fever so you can rest medicine"));
        map.add(new AcronymDetail("Tcob", "Taking care of business"));
        map.add(new AcronymDetail("InyfOa", "It’s not your father’s Oldsmobile anymore"));
        map.add(new AcronymDetail("Tmoam", "The mark of a man"));
        map.add(new AcronymDetail("Ce", "Changes everything"));
        map.add(new AcronymDetail("SptI", "Software powers the Internet"));
        map.add(new AcronymDetail("OIa", "Ore-Ida! It’s all-righta!"));
        map.add(new AcronymDetail("NrJr", "No rules Just right"));
        map.add(new AcronymDetail("GtSbtb", "Grab the Southwest by the bottle"));
        map.add(new AcronymDetail("Cos", "Catch our smile"));
        map.add(new AcronymDetail("Atmwoo", "Ask the man who owns one"));
        map.add(new AcronymDetail("Saoit", "Slightly ahead of its time"));
        map.add(new AcronymDetail("Tfsb", "The flavor says butter"));
        map.add(new AcronymDetail("TiybTiybod", "This is your brain This is your brain on drugs"));
        map.add(new AcronymDetail("Wwsnwbit", "We will sell no wine before its time"));
        map.add(new AcronymDetail("PFr", "Pepperidge Farm remembers"));
        map.add(new AcronymDetail("CaYitPg", "Come alive! You’re in the Pepsi generation"));
        map.add(new AcronymDetail("Ttoang", "The taste of a new generation"));
        map.add(new AcronymDetail("Pftwty", "Pepsi, for those who think young"));
        map.add(new AcronymDetail("Phts", "Pepsi-Cola hits the spot"));
        map.add(new AcronymDetail("Itatmtmatc", "It takes a tough man to make a tender chicken"));
        map.add(new AcronymDetail("Wtpg", "Where the pets go"));
        map.add(new AcronymDetail("TbkasiA", "The best kept automotive secret in America"));
        map.add(new AcronymDetail("TTl", "Talk They’ll listen"));
        map.add(new AcronymDetail("Ff", "Famously fresh"));
        map.add(new AcronymDetail("Las", "Lifts and separates"));
        map.add(new AcronymDetail("Tfdi", "The fun develops instantly"));
        map.add(new AcronymDetail("Gapotr", "Get a piece of the rock"));
        map.add(new AcronymDetail("Stsa", "Something to smile about"));
        map.add(new AcronymDetail("Mmmmm", "M’m, m’m, m’m, m’m, m’mtoasty!"));
        map.add(new AcronymDetail("Sos", "Spirit of service"));
        map.add(new AcronymDetail("Rtl", "Ride the light"));
        map.add(new AcronymDetail("Ygqwga", "You’ve got questions, we’ve got answers"));
        map.add(new AcronymDetail("Rkbd", "RAID kills bugs dead"));
        map.add(new AcronymDetail("IlismIbtc", "I liked it so much I bought the company"));
        map.add(new AcronymDetail("Hwdys", "How well do you share?"));
        map.add(new AcronymDetail("HdysrR", "How do you spell relief? R-O-L-A-I-D-S"));
        map.add(new AcronymDetail("Got", "Get out there"));
        map.add(new AcronymDetail("Ifl", "Ingredients for life"));
        map.add(new AcronymDetail("Es", "Experience success"));
        map.add(new AcronymDetail("Eylac", "Everything you love about coffee"));
        map.add(new AcronymDetail("TbtmMf", "The beer that made Milwaukee famous"));
        map.add(new AcronymDetail("FnSs", "Funny name Serious sandwich"));
        map.add(new AcronymDetail("SYkw", "Schhh! You know who?"));
        map.add(new AcronymDetail("Wtoi", "We turn on ideas"));
        map.add(new AcronymDetail("Sefambmfaw", "Strong enough for a man, but made for a woman"));
        map.add(new AcronymDetail("Tu", "The uncola"));
        map.add(new AcronymDetail("ISaBaIh", "It’s Shake and Bake, and I helped"));
        map.add(new AcronymDetail("Ftpwhewhee", "For the person who has everything, we have everything else"));
        map.add(new AcronymDetail("Cte", "Cover the earth"));
        map.add(new AcronymDetail("Atiap", "Always there in a pinch"));
        map.add(new AcronymDetail("WmtmtowWei", "We make the money the old-fashioned way We earn it"));
        map.add(new AcronymDetail("WanlSihtbg", "With a name like Smucker’s, it has to be good"));
        map.add(new AcronymDetail("MftbsoE", "Made from the best stuff on Earth"));
        map.add(new AcronymDetail("Yanftmatc", "You are now free to move about the country"));
        map.add(new AcronymDetail("Ntb", "Now, that’s better"));
        map.add(new AcronymDetail("Oyt", "Obey your thirst"));
        map.add(new AcronymDetail("Twe", "That was easy"));
        map.add(new AcronymDetail("SCSwtttgntwgt", "Sorry, Charlie Starkist wants tuna that tastes good, not tuna with good taste"));
        map.add(new AcronymDetail("Ef", "Eat fresh"));
        map.add(new AcronymDetail("Tnitc", "The network is the computer"));
        map.add(new AcronymDetail("Bs", "Better snacking"));
        map.add(new AcronymDetail("IinSijpod", "If it’s not SuperSoil, it’s just plain old dirt"));
        map.add(new AcronymDetail("Tne", "There’s no equal"));
        map.add(new AcronymDetail("Totb", "Think outside the bun"));
        map.add(new AcronymDetail("Hftb", "Head for the border"));
        map.add(new AcronymDetail("YqTB", "Yo quiero Taco Bell"));
        map.add(new AcronymDetail("EmPl", "Expect more Pay less"));
        map.add(new AcronymDetail("Irfts", "I’d rather fight than switch"));
        map.add(new AcronymDetail("IigbcigbT", "If it’s gotta be clean, it’s gotta be Tide"));
        map.add(new AcronymDetail("Talakot", "Takes a licking and keeps on ticking"));
        map.add(new AcronymDetail("Cf", "Choose freedom"));
        map.add(new AcronymDetail("Iwc", "Invest with confidence"));
        map.add(new AcronymDetail("Gtf", "Get the feeling"));
        map.add(new AcronymDetail("Srtafk", "Silly rabbit, trix are for kids"));
        map.add(new AcronymDetail("Avpoyw", "A vital part of your world"));
        map.add(new AcronymDetail("Ihr", "It’s hospital recommended"));
        map.add(new AcronymDetail("IiD", "Imagine it Done"));
        map.add(new AcronymDetail("Ttf", "Time to fly"));
        map.add(new AcronymDetail("Tmiatttw", "The mind is a terrible thing to waste"));
        map.add(new AcronymDetail("Tso‘", "The spirit of ‘76"));
        map.add(new AcronymDetail("WcBdfy", "What can Brown do for you?"));
        map.add(new AcronymDetail("Soobmaw", "Some of our best men are women"));
        map.add(new AcronymDetail("Fdlfdd", "Friends don’t let friends drive drunk"));
        map.add(new AcronymDetail("Oycpff", "Only you can prevent forest fires"));
        map.add(new AcronymDetail("Gahdp", "Give a hoot, don’t pollute"));
        map.add(new AcronymDetail("TftptM", "The few, the proud, the Marines"));
        map.add(new AcronymDetail("Wlfafgm", "We’re looking for a few good men"));
        map.add(new AcronymDetail("InajIaa", "It’s not a job It’s an adventure"));
        map.add(new AcronymDetail("Ttjyel", "The toughest job you’ll ever love"));
        map.add(new AcronymDetail("IchaV", "I coulda had a V-8!"));
        map.add(new AcronymDetail("Wnswfy", "We never stop working for you"));
        map.add(new AcronymDetail("Cyhmn", "Can you hear me now?Good!"));
        map.add(new AcronymDetail("Hmv", "His master’s voice"));
        map.add(new AcronymDetail("Ycalwb", "You’ve come a long way, baby"));
        map.add(new AcronymDetail("Vifl", "Virginia is for lovers"));
        map.add(new AcronymDetail("Ieywtb", "It’s everywhere you want to be"));
        map.add(new AcronymDetail("Vgtro", "Visine gets the red out"));
        map.add(new AcronymDetail("Ts", "Think small"));
        map.add(new AcronymDetail("Dw", "Drivers wanted"));
        map.add(new AcronymDetail("F", "Fahrvergnugen"));
        map.add(new AcronymDetail("Fl", "For life"));
        map.add(new AcronymDetail("AlpA", "Always low prices Always"));
        map.add(new AcronymDetail("Tns", "The next stage"));
        map.add(new AcronymDetail("Wtb", "Where’s the beef?"));
        map.add(new AcronymDetail("WAtowtf", "Western Airlines the only way to fly"));
        map.add(new AcronymDetail("Tboc", "The breakfast of champions"));
        map.add(new AcronymDetail("Ratc", "Ring around the collar"));
        map.add(new AcronymDetail("Falp", "For a living planet"));
        map.add(new AcronymDetail("Wmbd", "We’re moving beyond documents"));
        map.add(new AcronymDetail("B", "Believe"));
        map.add(new AcronymDetail("Lyfdtw", "Let your fingers do the walking"));
        map.add(new AcronymDetail("Wtmb", "Where technology means business"));
        map.add(new AcronymDetail("Tqgibtngo", "The quality goes in before the name goes on"));
        map.add(new AcronymDetail("Aitpwthhm", "Ace is the place with the helpful hardware man"));
        map.add(new AcronymDetail("Ppffowarii", "Plop plop, fizz fizz, oh what a relief it is"));
        map.add(new AcronymDetail("Tiee", "The incredible, edible egg"));
        map.add(new AcronymDetail("IasoB‘Bsom", "I am stuck on Band-Aids ‘cause Band-Aids stuck on me"));
        map.add(new AcronymDetail("BotBFabotb", "Bring out the Best Foods and bring out the best"));
        map.add(new AcronymDetail("Alddy", "A little dab’ll do ya"));
        map.add(new AcronymDetail("FaydtBfy", "For all you do, this Bud’s for you"));
        map.add(new AcronymDetail("WysBysia", "When you say Budweiser, you’ve said it all"));
        map.add(new AcronymDetail("Hiyw", "Have it your way"));
        map.add(new AcronymDetail("PcsfH", "Pure cane sugar from Hawaii"));
        map.add(new AcronymDetail("MMG", "M’m! M’m! Good!"));
        map.add(new AcronymDetail("StUiyC", "See the USA in your Chevrolet"));
        map.add(new AcronymDetail("WtbtCotS", "What’s the best tuna? Chicken of the Sea"));
        map.add(new AcronymDetail("ICBaIcts–bhtriacw", "I’m Chiquita Banana and I’ve come to say – bananas have to ripen in a certain way"));
        map.add(new AcronymDetail("Itrt", "It’s the real thing"));
        map.add(new AcronymDetail("Iltttwtsiph", "I’d like to teach the world to sing in perfect harmony"));
        map.add(new AcronymDetail("Cii", "Coke is it!"));
        map.add(new AcronymDetail("TgbwC", "Things go better with Coke"));
        map.add(new AcronymDetail("Wgatfy", "We’ve got a taste for you"));
        map.add(new AcronymDetail("JftfoiDC", "Just for the fun of it, Diet Coke"));
        map.add(new AcronymDetail("JfttoiDC", "Just for the taste of it, Diet Coke"));
        map.add(new AcronymDetail("Iaphapsap", "I’m a pepper, he’s a pepper, she’s a pepper"));
        map.add(new AcronymDetail("Icbhtb", "I can bring home the bacon"));
        map.add(new AcronymDetail("TbpowuiFiyc", "The best part of waking up is Folger’s in your cup"));
        map.add(new AcronymDetail("ItvotjG", "In the valley of the jolly--ho-ho-ho!--Green Giant"));
        map.add(new AcronymDetail("Ftlosw", "From the land of sky-blue waters"));
        map.add(new AcronymDetail("Iil(t", "Intel inside logo (four-note theme)"));
        map.add(new AcronymDetail("TarfJ", "There’s always room for J-E-L-L-0"));
        map.add(new AcronymDetail("Jmmmatwmmg", "Jell-O makes me mellow and the wiggle makes me giggle"));
        map.add(new AcronymDetail("SCPRK", "Snap! Crackle! Pop! Rice Krispies"));
        map.add(new AcronymDetail("GmabGmab", "Give me a break! Give me a break!"));
        map.add(new AcronymDetail("WwydfaKb", "What would you do for a Klondike bar?"));
        map.add(new AcronymDetail("AAsc", "And America spells cheeseK-R-A-F-T"));
        map.add(new AcronymDetail("HtgftlibL", "Here’s to good friendsTonight, tonight, let it be Lowenbrau"));
        map.add(new AcronymDetail("[ppt", "[Coffee pot percolator theme]"));
        map.add(new AcronymDetail("MsbwiMiM", "Maybe she’s born with it Maybe it’s Maybelline"));
        map.add(new AcronymDetail("Zzz", "Zoom, zoom, zoom"));
        map.add(new AcronymDetail("Ili", "I’m lovin’ it"));
        map.add(new AcronymDetail("Ydabt", "You deserve a break today"));
        map.add(new AcronymDetail("Tapsslcpooassb", "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun"));
        map.add(new AcronymDetail("Wltsys", "We love to see you smile"));
        map.add(new AcronymDetail("Mmmm", "Meow, meow, meow, meow"));
        map.add(new AcronymDetail("Iygttwgtb", "If you’ve got the time, we’ve got the beer"));
        map.add(new AcronymDetail("MCwcywhaetii", "Mr Clean will clean your whole house and everything that’s in it"));
        map.add(new AcronymDetail("Nioys", "Nationwide is on your side"));
        map.add(new AcronymDetail("NNmtvb", "N-E-S-T-L-E-S, Nestles makes the very bestchocolate"));
        map.add(new AcronymDetail("IwIwaOMW", "I wish I were an Oscar Mayer Wiener"));
        map.add(new AcronymDetail("MbhafniO", "My bologna has a first name, it’s O-S-C-A-R"));
        map.add(new AcronymDetail("Ptwty", "PepsiŃfor those who think young"));
        map.add(new AcronymDetail("Phts", "Pepsi hits the spot"));
        map.add(new AcronymDetail("YwwtywwybytwP", "You’ll wonder where the yellow went when you brush your teeth with Pepsodent"));
        map.add(new AcronymDetail("Syflansyd", "Sometimes you feel like a nut, sometimes you don’t"));
        map.add(new AcronymDetail("CfPM", "Call for Philip Morris"));
        map.add(new AcronymDetail("Nsllsfto", "Nothin’ says lovin’ like somethin’ from the oven"));
        map.add(new AcronymDetail("RtSFt", "Rice-a-Roni, the San Francisco treat"));
        map.add(new AcronymDetail("Agtdtd", "Away go troubles down the drain"));
        map.add(new AcronymDetail("NdlSL", "Nobody doesn’t like Sara Lee"));
        map.add(new AcronymDetail("WyooSyoob", "When you’re out of Schlitz, you’re out of beer"));
        map.add(new AcronymDetail("Sgyagwtf", "Singapore girl, you’re a great way to fly"));
        map.add(new AcronymDetail("Isisowawt", "It’s slinky, it’s slinky, oh what a wonderful toy"));
        map.add(new AcronymDetail("UoS", "Uh, oh, Spaghettios"));
        map.add(new AcronymDetail("LagnSFit", "Like a good neighbor, State Farm is there"));
        map.add(new AcronymDetail("Ryhiys", "Raise your hand if you’re sure"));
        map.add(new AcronymDetail("Hdyfahm", "How do you feed a hungry man?"));
        map.add(new AcronymDetail("Yctycttmwwts", "You can trust your car to the men who wear the star"));
        map.add(new AcronymDetail("Ilwydfm", "I love what you do for meToyota"));
        map.add(new AcronymDetail("TtttT", "Tum, tum, tum, tum, Tums"));
        map.add(new AcronymDetail("Ftfs(U", "Fly the friendly skies (of United)"));
        map.add(new AcronymDetail("Batycb", "Be all that you can be"));
        map.add(new AcronymDetail("Wtglacs", "Winston tastes good like a cigarette should"));
        map.add(new AcronymDetail("Dypdyf", "Double your pleasure, double your fun"));
        map.add(new AcronymDetail("YnfcuyZc", "You’re not fully clean until you’re Zestfully clean"));
    }
}
