package core;

public class HardCodedMnemonicMapLoader implements MnemonicMapLoader {

    @Override
    public void load(MnemonicMap map) {
        map.add(new MatchingMnemonic("BbA", new MatchingMnemonicDetail("Better by Adobe", "Adobe")));
        map.add(new MatchingMnemonic("Trwnbts", "The road will never be the same"));
        map.add(new MatchingMnemonic("Aaiaw", "Ask about it at work"));
        map.add(new MatchingMnemonic("Wkm", "We know money"));
        map.add(new MatchingMnemonic("Std", "Stronger than dirt"));
        map.add(new MatchingMnemonic("IcbIatwt", "I can’t believe I ate the whole thing"));
        map.add(new MatchingMnemonic("Mmtsm", "Mama mia, thatsa spicy meatball"));
        map.add(new MatchingMnemonic("Tiyli", "Try it, you’ll like it"));
        map.add(new MatchingMnemonic("Trgo", "The relief goes on"));
        map.add(new MatchingMnemonic("YighwA", "You’re in good hands with Allstate"));
        map.add(new MatchingMnemonic("DyddA", "Doesn’t your dog deserve Alpo?"));
        map.add(new MatchingMnemonic("Wlad", "Works like a dream"));
        map.add(new MatchingMnemonic("Ssita", "Something special in the air"));
        map.add(new MatchingMnemonic("Btpoc", "Behold the power of cheese"));
        map.add(new MatchingMnemonic("Dlhwi", "Don’t leave home without it"));
        map.add(new MatchingMnemonic("Dm", "Do more"));
        map.add(new MatchingMnemonic("MlMc", "My life My card"));
        map.add(new MatchingMnemonic("Ffffr", "For fast, fast, fast relief"));
        map.add(new MatchingMnemonic("Lr", "Legendary reliability"));
        map.add(new MatchingMnemonic("Td", "Think different"));
        map.add(new MatchingMnemonic("Tptbyb", "The power to be your best"));
        map.add(new MatchingMnemonic("Totb", "Think outside the box"));
        map.add(new MatchingMnemonic("Roats", "Reach out and touch someone"));
        map.add(new MatchingMnemonic("Twnc", "The world’s networking company"));
        map.add(new MatchingMnemonic("Nf", "Never follow"));
        map.add(new MatchingMnemonic("Wth", "We try harder"));
        map.add(new MatchingMnemonic("Hs", "Higher standards"));
        map.add(new MatchingMnemonic("Tyfys", "Thank you for your support"));
        map.add(new MatchingMnemonic("Bww", "Bayer works wonders"));
        map.add(new MatchingMnemonic("FmB", "Flick my Bic"));
        map.add(new MatchingMnemonic("Wmc", "We mean clean"));
        map.add(new MatchingMnemonic("LmCiu", "Life’s messy Clean it up!"));
        map.add(new MatchingMnemonic("Sdp", "Sheer driving pleasure"));
        map.add(new MatchingMnemonic("Tudm", "The ultimate driving machine"));
        map.add(new MatchingMnemonic("Bstr", "Better sound through research"));
        map.add(new MatchingMnemonic("Tqp", "The quicker picker-upper"));
        map.add(new MatchingMnemonic("Wygifi", "When you’ve got it, flaunt it"));
        map.add(new MatchingMnemonic("FittrwB", "Fill it to the rim with Brim"));
        map.add(new MatchingMnemonic("Htatmom", "Hope, triumph, and the miracle of medicine"));
        map.add(new MatchingMnemonic("Twtf", "The way to fly"));
        map.add(new MatchingMnemonic("Twfa", "The world’s favourite airline"));
        map.add(new MatchingMnemonic("W", "Wassup?!"));
        map.add(new MatchingMnemonic("Tkob", "The king of beers"));
        map.add(new MatchingMnemonic("Ijtb", "It just tastes better"));
        map.add(new MatchingMnemonic("Hiyw", "Have it your way"));
        map.add(new MatchingMnemonic("Bt", "Break through"));
        map.add(new MatchingMnemonic("Acawtawa", "A can a week, that’s all we ask"));
        map.add(new MatchingMnemonic("Gm", "Got milk?"));
        map.add(new MatchingMnemonic("Ctma", "Calgon, take me away"));
        map.add(new MatchingMnemonic("Blamlo", "Between love and madness lies obsession"));
        map.add(new MatchingMnemonic("NcbmamC", "Nothing comes between me and my Calvins"));
        map.add(new MatchingMnemonic("Iwamfac", "I’d walk a mile for a camel"));
        map.add(new MatchingMnemonic("Fnp", "For negative people"));
        map.add(new MatchingMnemonic("Wiyw", "What’s in your wallet?"));
        map.add(new MatchingMnemonic("Fvsd", "For virtually spotless dishes"));
        map.add(new MatchingMnemonic("Tpie", "Turning partnership into energy"));
        map.add(new MatchingMnemonic("PdstC", "Please don’t squeeze the Charmin"));
        map.add(new MatchingMnemonic("Gyob", "Get your own box"));
        map.add(new MatchingMnemonic("Asml", "A silly millimeter longer"));
        map.add(new MatchingMnemonic("Lar", "Like a rock"));
        map.add(new MatchingMnemonic("InntfMN", "It’s not nice to fool Mother Nature"));
        map.add(new MatchingMnemonic("Ics", "Inspiration comes standard"));
        map.add(new MatchingMnemonic("Wybr", "Will you be ready?"));
        map.add(new MatchingMnemonic("EtIg", "Empowering the Internet generation"));
        map.add(new MatchingMnemonic("Lr", "Live richly"));
        map.add(new MatchingMnemonic("IIoollmliaab", "If I’ve only one life, let me live it as a blonde"));
        map.add(new MatchingMnemonic("Dsods", "Does she or doesn’t she?"));
        map.add(new MatchingMnemonic("Tafc", "The antidote for civilization"));
        map.add(new MatchingMnemonic("Tsfcat", "The source for computing and technology"));
        map.add(new MatchingMnemonic("Tmtnin", "The most trusted name in news"));
        map.add(new MatchingMnemonic("Cryb", "Coca-Cola refreshes you best"));
        map.add(new MatchingMnemonic("Tptr", "The pause that refreshes"));
        map.add(new MatchingMnemonic("Hacas", "Have a coke and smile"));
        map.add(new MatchingMnemonic("Tsb", "The silver bullet"));
        map.add(new MatchingMnemonic("CTfool", "Cotton The fabric of our lives"));
        map.add(new MatchingMnemonic("Iywtcsaw", "If you want to capture someone’s attention, whisper"));
        map.add(new MatchingMnemonic("Hbsfl", "Healthy, beautiful smiles for life"));
        map.add(new MatchingMnemonic("LMnc", "Look, Ma, no cavities!"));
        map.add(new MatchingMnemonic("CwktC", "Cooks who know trust Crisco"));
        map.add(new MatchingMnemonic("Lifl", "Love it for life"));
        map.add(new MatchingMnemonic("Adif", "A diamond is forever"));
        map.add(new MatchingMnemonic("EaD", "Easy as Dell"));
        map.add(new MatchingMnemonic("Yltwwf", "You’ll love the way we fly"));
        map.add(new MatchingMnemonic("Wltfais", "We love to fly and it shows"));
        map.add(new MatchingMnemonic("Wcn", "We’re cooking now"));
        map.add(new MatchingMnemonic("Rtjom", "Restoring the joy of motion"));
        map.add(new MatchingMnemonic("Wmtw", "We move the world"));
        map.add(new MatchingMnemonic("YTnB", "Yellow The new Brown"));
        map.add(new MatchingMnemonic("CBftGfy", "Competition Bad for them Great for you"));
        map.add(new MatchingMnemonic("AygyuDDywed", "Aren’t you glad you use Dial? Don’t you wish everybody did?"));
        map.add(new MatchingMnemonic("Thpoe", "The happiest place on earth"));
        map.add(new MatchingMnemonic("Ttmtd", "Time to make the doughnuts"));
        map.add(new MatchingMnemonic("Tmos", "The miracles of science"));
        map.add(new MatchingMnemonic("Bltc", "Better living through chemistry"));
        map.add(new MatchingMnemonic("Tpoaou", "The power of all of us"));
        map.add(new MatchingMnemonic("Twom", "The world’s online marketplace"));
        map.add(new MatchingMnemonic("WEHtpl", "When EF Hutton talks, people listen"));
        map.add(new MatchingMnemonic("NslaE", "Nothing sucks like an Electrolux"));
        map.add(new MatchingMnemonic("Wycfc", "When you’re crazy for chicken"));
        map.add(new MatchingMnemonic("Ikgagag", "It keeps going, and going, and going"));
        map.add(new MatchingMnemonic("Sywf", "See your way forward"));
        map.add(new MatchingMnemonic("Qiewd", "Quality in everything we do"));
        map.add(new MatchingMnemonic("Patiyt", "Put a tiger in your tank"));
        map.add(new MatchingMnemonic("DjtTr", "Don’t just travel Travel right"));
        map.add(new MatchingMnemonic("Gtietr", "Good taste is easy to recognize"));
        map.add(new MatchingMnemonic("ObitAd", "Our business is the American dream"));
        map.add(new MatchingMnemonic("RiF", "Relax, it’s FedEx"));
        map.add(new MatchingMnemonic("Twot", "The world on time"));
        map.add(new MatchingMnemonic("Wiaphtbto", "When it absolutely, positively has to be there overnight"));
        map.add(new MatchingMnemonic("PLG", "Play Laugh Grow"));
        map.add(new MatchingMnemonic("Injfba", "It’s not just for breakfast anymore"));
        map.add(new MatchingMnemonic("Bftra", "Built for the road ahead"));
        map.add(new MatchingMnemonic("Fhabi", "Ford has a better idea"));
        map.add(new MatchingMnemonic("Qijo", "Quality is job one"));
        map.add(new MatchingMnemonic("F–Afb", "Fosters – Australian for beer"));
        map.add(new MatchingMnemonic("Fab", "Fair and balanced"));
        map.add(new MatchingMnemonic("Eif", "Extinct is forever"));
        map.add(new MatchingMnemonic("Siwf", "Say it with flowers"));
        map.add(new MatchingMnemonic("Iaw", "Imagination at work"));
        map.add(new MatchingMnemonic("Wbgttl", "We bring good things to life"));
        map.add(new MatchingMnemonic("Ctmoyl", "Celebrate the moments of your life"));
        map.add(new MatchingMnemonic("Twttw", "Two words to the wise"));
        map.add(new MatchingMnemonic("Baob", "Babies are our business"));
        map.add(new MatchingMnemonic("SybbaGb", "Shouldn’t your baby be a Gerber baby?"));
        map.add(new MatchingMnemonic("MwItIkh", "My wife, I think I’ll keep her"));
        map.add(new MatchingMnemonic("Lsfs", "Look sharp, feel sharp"));
        map.add(new MatchingMnemonic("Tbamcg", "The best a man can get"));
        map.add(new MatchingMnemonic("Nl‘sys", "Never let ‘em see you sweat"));
        map.add(new MatchingMnemonic("DgmGG", "Don’t get mad Get GLAD"));
        map.add(new MatchingMnemonic("TbtitwhGwaot", "The best tires in the world have Goodyear written all over them"));
        map.add(new MatchingMnemonic("Ltdtu", "Leave the driving to us"));
        map.add(new MatchingMnemonic("PmdyhaGP", "Pardon me, do you have any Grey Poupon?"));
        map.add(new MatchingMnemonic("Iagttba", "It’s a great time to be alive"));
        map.add(new MatchingMnemonic("DbvafH", "Don’t be vague, ask for Haig"));
        map.add(new MatchingMnemonic("Wycetstvb", "When you care enough to send the very best"));
        map.add(new MatchingMnemonic("AbbRbc", "American by birth Rebel by choice"));
        map.add(new MatchingMnemonic("HHaanHP", "Hey! How about a nice Hawaiian Punch?"));
        map.add(new MatchingMnemonic("Wataha", "We answer to a higher authority"));
        map.add(new MatchingMnemonic("Hpyitds", "Hertz puts you in the driver’s seat"));
        map.add(new MatchingMnemonic("5v", "57 varieties"));
        map.add(new MatchingMnemonic("I", "Invent"));
        map.add(new MatchingMnemonic("Pptwo", "Pleasing people the world over"));
        map.add(new MatchingMnemonic("Tpod", "The power of dreams"));
        map.add(new MatchingMnemonic("Wtcf", "Where’s the cream filling?"));
        map.add(new MatchingMnemonic("Wbyesotw", "We’re behind you every step of the way"));
        map.add(new MatchingMnemonic("Sfasp", "Solutions for a small planet"));
        map.add(new MatchingMnemonic("II", "Intel Inside"));
        map.add(new MatchingMnemonic("MybIlit", "Manly yes, but I like it, too"));
        map.add(new MatchingMnemonic("PcpI", "Pure clean, pure Ivory"));
        map.add(new MatchingMnemonic("9p", "9944% pure"));
        map.add(new MatchingMnemonic("Jb", "Jack’s back!"));
        map.add(new MatchingMnemonic("DdiDi", "Don’t dream it Drive it"));
        map.add(new MatchingMnemonic("Amfd", "America’s most famous dessert"));
        map.add(new MatchingMnemonic("NrlaD", "Nothing runs like a Deere"));
        map.add(new MatchingMnemonic("Trrie", "The right relationship is everything"));
        map.add(new MatchingMnemonic("1jf1k", "100% juice for 100% kids"));
        map.add(new MatchingMnemonic("T", "Thrive"));
        map.add(new MatchingMnemonic("EkbwK", "Every kiss begins with Kay"));
        map.add(new MatchingMnemonic("Tg", "They’re g-r-r-r-eat!"));
        map.add(new MatchingMnemonic("Sas", "Start aging smart"));
        map.add(new MatchingMnemonic("Fg", "Finger-lickin’ good!"));
        map.add(new MatchingMnemonic("NdclK", "Nobody does chicken like KFC"));
        map.add(new MatchingMnemonic("KtMa", "Kid tested Mother approved"));
        map.add(new MatchingMnemonic("SmSl", "Share moments Share life"));
        map.add(new MatchingMnemonic("Itfc", "It’s time for clarity"));
        map.add(new MatchingMnemonic("Whhsh", "What happens here, stays here"));
        map.add(new MatchingMnemonic("Bcejo", "Betcha can’t eat just one"));
        map.add(new MatchingMnemonic("Wbcyw", "When banks compete, you win"));
        map.add(new MatchingMnemonic("Trpop", "The relentless pursuit of perfection"));
        map.add(new MatchingMnemonic("IfaIcgu", "I’ve fallen and I can’t get up"));
        map.add(new MatchingMnemonic("HMli", "Hey, Mikeyhe likes it!"));
        map.add(new MatchingMnemonic("Aabbnab", "Always a bridesmaid, but never a bride"));
        map.add(new MatchingMnemonic("BIwi", "Because I’m worth it"));
        map.add(new MatchingMnemonic("Md", "Magically delicious"));
        map.add(new MatchingMnemonic("LSmft", "Lucky Strike means fine tobacco"));
        map.add(new MatchingMnemonic("Cvttc", "Creating value through true convergence"));
        map.add(new MatchingMnemonic("Miymniyh", "Melts in your mouth, not in your hands"));
        map.add(new MatchingMnemonic("CtMC", "Come to Marlboro Country"));
        map.add(new MatchingMnemonic("TasttmcbFeetM", "There are some things that money can’t buy For everything else there’s MasterCard"));
        map.add(new MatchingMnemonic("Gttld", "Good to the last drop"));
        map.add(new MatchingMnemonic("IwmM", "I want my Maypo"));
        map.add(new MatchingMnemonic("Oratlgit", "Our repairmen are the loneliest guys in town"));
        map.add(new MatchingMnemonic("Pftr", "Passion for the road"));
        map.add(new MatchingMnemonic("DssM", "Did somebody say McDonald’s?"));
        map.add(new MatchingMnemonic("IiloiiM", "Is it live or is it Memorex?"));
        map.add(new MatchingMnemonic("Tsgcafibn", "Tastes so good cats ask for it by name"));
        map.add(new MatchingMnemonic("MiboA", "Merrill-Lynch is bullish on America"));
        map.add(new MatchingMnemonic("Mmgm", "MGM means great movies"));
        map.add(new MatchingMnemonic("Bsmiroyt", "Because so much is riding on your tires"));
        map.add(new MatchingMnemonic("LtcNtt", "Lose the carbs Not the taste"));
        map.add(new MatchingMnemonic("YpOp", "Your potential Our passion"));
        map.add(new MatchingMnemonic("Wdywtgt", "Where do you want to go today?"));
        map.add(new MatchingMnemonic("IMt", "It’s Miller time!"));
        map.add(new MatchingMnemonic("Tcobb", "The champagne of bottled beer"));
        map.add(new MatchingMnemonic("EyawiabAl", "Everything you always wanted in a beer And less"));
        map.add(new MatchingMnemonic("Tglf", "Tastes great, less filling"));
        map.add(new MatchingMnemonic("Wuad", "Wake up and drive"));
        map.add(new MatchingMnemonic("Ocaat", "One client at a time"));
        map.add(new MatchingMnemonic("Wirip", "When it rains, it pours"));
        map.add(new MatchingMnemonic("Mwm", "Medicine with muscle"));
        map.add(new MatchingMnemonic("DtD", "Do the Dew"));
        map.add(new MatchingMnemonic("BIwfd", "Beef It’s what’s for dinner"));
        map.add(new MatchingMnemonic("Tabooc", "Take a bite out of crime"));
        map.add(new MatchingMnemonic("PTowm", "Pork The other white meat"));
        map.add(new MatchingMnemonic("YclalfadBu", "You could learn a lot from a dummy Buckle up!"));
        map.add(new MatchingMnemonic("MsT", "Must see TV"));
        map.add(new MatchingMnemonic("Booto", "Break out of the ordinary"));
        map.add(new MatchingMnemonic("IlNY", "I love New York"));
        map.add(new MatchingMnemonic("Atntftp", "All the news that’s fit to print"));
        map.add(new MatchingMnemonic("Jdi", "Just do it"));
        map.add(new MatchingMnemonic("Athoti", "At the heart of the image"));
        map.add(new MatchingMnemonic("OffakNL", "Only fit for a king Nine Lives"));
        map.add(new MatchingMnemonic("Etr", "Enjoy the ride"));
        map.add(new MatchingMnemonic("Cp", "Connecting people"));
        map.add(new MatchingMnemonic("Tiao", "Take it all off"));
        map.add(new MatchingMnemonic("Tnsscashfsycrm", "The nighttime sniffling sneezing coughing aching stuffy head fever so you can rest medicine"));
        map.add(new MatchingMnemonic("Tcob", "Taking care of business"));
        map.add(new MatchingMnemonic("InyfOa", "It’s not your father’s Oldsmobile anymore"));
        map.add(new MatchingMnemonic("Tmoam", "The mark of a man"));
        map.add(new MatchingMnemonic("Ce", "Changes everything"));
        map.add(new MatchingMnemonic("SptI", "Software powers the Internet"));
        map.add(new MatchingMnemonic("OIa", "Ore-Ida! It’s all-righta!"));
        map.add(new MatchingMnemonic("NrJr", "No rules Just right"));
        map.add(new MatchingMnemonic("GtSbtb", "Grab the Southwest by the bottle"));
        map.add(new MatchingMnemonic("Cos", "Catch our smile"));
        map.add(new MatchingMnemonic("Atmwoo", "Ask the man who owns one"));
        map.add(new MatchingMnemonic("Saoit", "Slightly ahead of its time"));
        map.add(new MatchingMnemonic("Tfsb", "The flavor says butter"));
        map.add(new MatchingMnemonic("TiybTiybod", "This is your brain This is your brain on drugs"));
        map.add(new MatchingMnemonic("Wwsnwbit", "We will sell no wine before its time"));
        map.add(new MatchingMnemonic("PFr", "Pepperidge Farm remembers"));
        map.add(new MatchingMnemonic("CaYitPg", "Come alive! You’re in the Pepsi generation"));
        map.add(new MatchingMnemonic("Ttoang", "The taste of a new generation"));
        map.add(new MatchingMnemonic("Pftwty", "Pepsi, for those who think young"));
        map.add(new MatchingMnemonic("Phts", "Pepsi-Cola hits the spot"));
        map.add(new MatchingMnemonic("Itatmtmatc", "It takes a tough man to make a tender chicken"));
        map.add(new MatchingMnemonic("Wtpg", "Where the pets go"));
        map.add(new MatchingMnemonic("TbkasiA", "The best kept automotive secret in America"));
        map.add(new MatchingMnemonic("TTl", "Talk They’ll listen"));
        map.add(new MatchingMnemonic("Ff", "Famously fresh"));
        map.add(new MatchingMnemonic("Las", "Lifts and separates"));
        map.add(new MatchingMnemonic("Tfdi", "The fun develops instantly"));
        map.add(new MatchingMnemonic("Gapotr", "Get a piece of the rock"));
        map.add(new MatchingMnemonic("Stsa", "Something to smile about"));
        map.add(new MatchingMnemonic("Mmmmm", "M’m, m’m, m’m, m’m, m’mtoasty!"));
        map.add(new MatchingMnemonic("Sos", "Spirit of service"));
        map.add(new MatchingMnemonic("Rtl", "Ride the light"));
        map.add(new MatchingMnemonic("Ygqwga", "You’ve got questions, we’ve got answers"));
        map.add(new MatchingMnemonic("Rkbd", "RAID kills bugs dead"));
        map.add(new MatchingMnemonic("IlismIbtc", "I liked it so much I bought the company"));
        map.add(new MatchingMnemonic("Hwdys", "How well do you share?"));
        map.add(new MatchingMnemonic("HdysrR", "How do you spell relief? R-O-L-A-I-D-S"));
        map.add(new MatchingMnemonic("Got", "Get out there"));
        map.add(new MatchingMnemonic("Ifl", "Ingredients for life"));
        map.add(new MatchingMnemonic("Es", "Experience success"));
        map.add(new MatchingMnemonic("Eylac", "Everything you love about coffee"));
        map.add(new MatchingMnemonic("TbtmMf", "The beer that made Milwaukee famous"));
        map.add(new MatchingMnemonic("FnSs", "Funny name Serious sandwich"));
        map.add(new MatchingMnemonic("SYkw", "Schhh! You know who?"));
        map.add(new MatchingMnemonic("Wtoi", "We turn on ideas"));
        map.add(new MatchingMnemonic("Sefambmfaw", "Strong enough for a man, but made for a woman"));
        map.add(new MatchingMnemonic("Tu", "The uncola"));
        map.add(new MatchingMnemonic("ISaBaIh", "It’s Shake and Bake, and I helped"));
        map.add(new MatchingMnemonic("Ftpwhewhee", "For the person who has everything, we have everything else"));
        map.add(new MatchingMnemonic("Cte", "Cover the earth"));
        map.add(new MatchingMnemonic("Atiap", "Always there in a pinch"));
        map.add(new MatchingMnemonic("WmtmtowWei", "We make the money the old-fashioned way We earn it"));
        map.add(new MatchingMnemonic("WanlSihtbg", "With a name like Smucker’s, it has to be good"));
        map.add(new MatchingMnemonic("MftbsoE", "Made from the best stuff on Earth"));
        map.add(new MatchingMnemonic("Yanftmatc", "You are now free to move about the country"));
        map.add(new MatchingMnemonic("Ntb", "Now, that’s better"));
        map.add(new MatchingMnemonic("Oyt", "Obey your thirst"));
        map.add(new MatchingMnemonic("Twe", "That was easy"));
        map.add(new MatchingMnemonic("SCSwtttgntwgt", "Sorry, Charlie Starkist wants tuna that tastes good, not tuna with good taste"));
        map.add(new MatchingMnemonic("Ef", "Eat fresh"));
        map.add(new MatchingMnemonic("Tnitc", "The network is the computer"));
        map.add(new MatchingMnemonic("Bs", "Better snacking"));
        map.add(new MatchingMnemonic("IinSijpod", "If it’s not SuperSoil, it’s just plain old dirt"));
        map.add(new MatchingMnemonic("Tne", "There’s no equal"));
        map.add(new MatchingMnemonic("Totb", "Think outside the bun"));
        map.add(new MatchingMnemonic("Hftb", "Head for the border"));
        map.add(new MatchingMnemonic("YqTB", "Yo quiero Taco Bell"));
        map.add(new MatchingMnemonic("EmPl", "Expect more Pay less"));
        map.add(new MatchingMnemonic("Irfts", "I’d rather fight than switch"));
        map.add(new MatchingMnemonic("IigbcigbT", "If it’s gotta be clean, it’s gotta be Tide"));
        map.add(new MatchingMnemonic("Talakot", "Takes a licking and keeps on ticking"));
        map.add(new MatchingMnemonic("Cf", "Choose freedom"));
        map.add(new MatchingMnemonic("Iwc", "Invest with confidence"));
        map.add(new MatchingMnemonic("Gtf", "Get the feeling"));
        map.add(new MatchingMnemonic("Srtafk", "Silly rabbit, trix are for kids"));
        map.add(new MatchingMnemonic("Avpoyw", "A vital part of your world"));
        map.add(new MatchingMnemonic("Ihr", "It’s hospital recommended"));
        map.add(new MatchingMnemonic("IiD", "Imagine it Done"));
        map.add(new MatchingMnemonic("Ttf", "Time to fly"));
        map.add(new MatchingMnemonic("Tmiatttw", "The mind is a terrible thing to waste"));
        map.add(new MatchingMnemonic("Tso‘", "The spirit of ‘76"));
        map.add(new MatchingMnemonic("WcBdfy", "What can Brown do for you?"));
        map.add(new MatchingMnemonic("Soobmaw", "Some of our best men are women"));
        map.add(new MatchingMnemonic("Fdlfdd", "Friends don’t let friends drive drunk"));
        map.add(new MatchingMnemonic("Oycpff", "Only you can prevent forest fires"));
        map.add(new MatchingMnemonic("Gahdp", "Give a hoot, don’t pollute"));
        map.add(new MatchingMnemonic("TftptM", "The few, the proud, the Marines"));
        map.add(new MatchingMnemonic("Wlfafgm", "We’re looking for a few good men"));
        map.add(new MatchingMnemonic("InajIaa", "It’s not a job It’s an adventure"));
        map.add(new MatchingMnemonic("Ttjyel", "The toughest job you’ll ever love"));
        map.add(new MatchingMnemonic("IchaV", "I coulda had a V-8!"));
        map.add(new MatchingMnemonic("Wnswfy", "We never stop working for you"));
        map.add(new MatchingMnemonic("Cyhmn", "Can you hear me now?Good!"));
        map.add(new MatchingMnemonic("Hmv", "His master’s voice"));
        map.add(new MatchingMnemonic("Ycalwb", "You’ve come a long way, baby"));
        map.add(new MatchingMnemonic("Vifl", "Virginia is for lovers"));
        map.add(new MatchingMnemonic("Ieywtb", "It’s everywhere you want to be"));
        map.add(new MatchingMnemonic("Vgtro", "Visine gets the red out"));
        map.add(new MatchingMnemonic("Ts", "Think small"));
        map.add(new MatchingMnemonic("Dw", "Drivers wanted"));
        map.add(new MatchingMnemonic("F", "Fahrvergnugen"));
        map.add(new MatchingMnemonic("Fl", "For life"));
        map.add(new MatchingMnemonic("AlpA", "Always low prices Always"));
        map.add(new MatchingMnemonic("Tns", "The next stage"));
        map.add(new MatchingMnemonic("Wtb", "Where’s the beef?"));
        map.add(new MatchingMnemonic("WAtowtf", "Western Airlines the only way to fly"));
        map.add(new MatchingMnemonic("Tboc", "The breakfast of champions"));
        map.add(new MatchingMnemonic("Ratc", "Ring around the collar"));
        map.add(new MatchingMnemonic("Falp", "For a living planet"));
        map.add(new MatchingMnemonic("Wmbd", "We’re moving beyond documents"));
        map.add(new MatchingMnemonic("B", "Believe"));
        map.add(new MatchingMnemonic("Lyfdtw", "Let your fingers do the walking"));
        map.add(new MatchingMnemonic("Wtmb", "Where technology means business"));
        map.add(new MatchingMnemonic("Tqgibtngo", "The quality goes in before the name goes on"));
        map.add(new MatchingMnemonic("Aitpwthhm", "Ace is the place with the helpful hardware man"));
        map.add(new MatchingMnemonic("Ppffowarii", "Plop plop, fizz fizz, oh what a relief it is"));
        map.add(new MatchingMnemonic("Tiee", "The incredible, edible egg"));
        map.add(new MatchingMnemonic("IasoB‘Bsom", "I am stuck on Band-Aids ‘cause Band-Aids stuck on me"));
        map.add(new MatchingMnemonic("BotBFabotb", "Bring out the Best Foods and bring out the best"));
        map.add(new MatchingMnemonic("Alddy", "A little dab’ll do ya"));
        map.add(new MatchingMnemonic("FaydtBfy", "For all you do, this Bud’s for you"));
        map.add(new MatchingMnemonic("WysBysia", "When you say Budweiser, you’ve said it all"));
        map.add(new MatchingMnemonic("Hiyw", "Have it your way"));
        map.add(new MatchingMnemonic("PcsfH", "Pure cane sugar from Hawaii"));
        map.add(new MatchingMnemonic("MMG", "M’m! M’m! Good!"));
        map.add(new MatchingMnemonic("StUiyC", "See the USA in your Chevrolet"));
        map.add(new MatchingMnemonic("WtbtCotS", "What’s the best tuna? Chicken of the Sea"));
        map.add(new MatchingMnemonic("ICBaIcts–bhtriacw", "I’m Chiquita Banana and I’ve come to say – bananas have to ripen in a certain way"));
        map.add(new MatchingMnemonic("Itrt", "It’s the real thing"));
        map.add(new MatchingMnemonic("Iltttwtsiph", "I’d like to teach the world to sing in perfect harmony"));
        map.add(new MatchingMnemonic("Cii", "Coke is it!"));
        map.add(new MatchingMnemonic("TgbwC", "Things go better with Coke"));
        map.add(new MatchingMnemonic("Wgatfy", "We’ve got a taste for you"));
        map.add(new MatchingMnemonic("JftfoiDC", "Just for the fun of it, Diet Coke"));
        map.add(new MatchingMnemonic("JfttoiDC", "Just for the taste of it, Diet Coke"));
        map.add(new MatchingMnemonic("Iaphapsap", "I’m a pepper, he’s a pepper, she’s a pepper"));
        map.add(new MatchingMnemonic("Icbhtb", "I can bring home the bacon"));
        map.add(new MatchingMnemonic("TbpowuiFiyc", "The best part of waking up is Folger’s in your cup"));
        map.add(new MatchingMnemonic("ItvotjG", "In the valley of the jolly--ho-ho-ho!--Green Giant"));
        map.add(new MatchingMnemonic("Ftlosw", "From the land of sky-blue waters"));
        map.add(new MatchingMnemonic("Iil(t", "Intel inside logo (four-note theme)"));
        map.add(new MatchingMnemonic("TarfJ", "There’s always room for J-E-L-L-0"));
        map.add(new MatchingMnemonic("Jmmmatwmmg", "Jell-O makes me mellow and the wiggle makes me giggle"));
        map.add(new MatchingMnemonic("SCPRK", "Snap! Crackle! Pop! Rice Krispies"));
        map.add(new MatchingMnemonic("GmabGmab", "Give me a break! Give me a break!"));
        map.add(new MatchingMnemonic("WwydfaKb", "What would you do for a Klondike bar?"));
        map.add(new MatchingMnemonic("AAsc", "And America spells cheeseK-R-A-F-T"));
        map.add(new MatchingMnemonic("HtgftlibL", "Here’s to good friendsTonight, tonight, let it be Lowenbrau"));
        map.add(new MatchingMnemonic("[ppt", "[Coffee pot percolator theme]"));
        map.add(new MatchingMnemonic("MsbwiMiM", "Maybe she’s born with it Maybe it’s Maybelline"));
        map.add(new MatchingMnemonic("Zzz", "Zoom, zoom, zoom"));
        map.add(new MatchingMnemonic("Ili", "I’m lovin’ it"));
        map.add(new MatchingMnemonic("Ydabt", "You deserve a break today"));
        map.add(new MatchingMnemonic("Tapsslcpooassb", "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun"));
        map.add(new MatchingMnemonic("Wltsys", "We love to see you smile"));
        map.add(new MatchingMnemonic("Mmmm", "Meow, meow, meow, meow"));
        map.add(new MatchingMnemonic("Iygttwgtb", "If you’ve got the time, we’ve got the beer"));
        map.add(new MatchingMnemonic("MCwcywhaetii", "Mr Clean will clean your whole house and everything that’s in it"));
        map.add(new MatchingMnemonic("Nioys", "Nationwide is on your side"));
        map.add(new MatchingMnemonic("NNmtvb", "N-E-S-T-L-E-S, Nestles makes the very bestchocolate"));
        map.add(new MatchingMnemonic("IwIwaOMW", "I wish I were an Oscar Mayer Wiener"));
        map.add(new MatchingMnemonic("MbhafniO", "My bologna has a first name, it’s O-S-C-A-R"));
        map.add(new MatchingMnemonic("Ptwty", "PepsiŃfor those who think young"));
        map.add(new MatchingMnemonic("Phts", "Pepsi hits the spot"));
        map.add(new MatchingMnemonic("YwwtywwybytwP", "You’ll wonder where the yellow went when you brush your teeth with Pepsodent"));
        map.add(new MatchingMnemonic("Syflansyd", "Sometimes you feel like a nut, sometimes you don’t"));
        map.add(new MatchingMnemonic("CfPM", "Call for Philip Morris"));
        map.add(new MatchingMnemonic("Nsllsfto", "Nothin’ says lovin’ like somethin’ from the oven"));
        map.add(new MatchingMnemonic("RtSFt", "Rice-a-Roni, the San Francisco treat"));
        map.add(new MatchingMnemonic("Agtdtd", "Away go troubles down the drain"));
        map.add(new MatchingMnemonic("NdlSL", "Nobody doesn’t like Sara Lee"));
        map.add(new MatchingMnemonic("WyooSyoob", "When you’re out of Schlitz, you’re out of beer"));
        map.add(new MatchingMnemonic("Sgyagwtf", "Singapore girl, you’re a great way to fly"));
        map.add(new MatchingMnemonic("Isisowawt", "It’s slinky, it’s slinky, oh what a wonderful toy"));
        map.add(new MatchingMnemonic("UoS", "Uh, oh, Spaghettios"));
        map.add(new MatchingMnemonic("LagnSFit", "Like a good neighbor, State Farm is there"));
        map.add(new MatchingMnemonic("Ryhiys", "Raise your hand if you’re sure"));
        map.add(new MatchingMnemonic("Hdyfahm", "How do you feed a hungry man?"));
        map.add(new MatchingMnemonic("Yctycttmwwts", "You can trust your car to the men who wear the star"));
        map.add(new MatchingMnemonic("Ilwydfm", "I love what you do for meToyota"));
        map.add(new MatchingMnemonic("TtttT", "Tum, tum, tum, tum, Tums"));
        map.add(new MatchingMnemonic("Ftfs(U", "Fly the friendly skies (of United)"));
        map.add(new MatchingMnemonic("Batycb", "Be all that you can be"));
        map.add(new MatchingMnemonic("Wtglacs", "Winston tastes good like a cigarette should"));
        map.add(new MatchingMnemonic("Dypdyf", "Double your pleasure, double your fun"));
        map.add(new MatchingMnemonic("YnfcuyZc", "You’re not fully clean until you’re Zestfully clean"));
    }
}
